<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class departamentoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('departamento')->insert(
            [
                'cod'=>'0',
                'Description'=>'No definido',
                'pais_cod'=>'0'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'91',
                'Description'=>'Amazonas',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'05',
                'Description'=>'Antioquia',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'81',
                'Description'=>'Arauca',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'08',
                'Description'=>'Atlántico',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'11',
                'Description'=>'Bogotá',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'13',
                'Description'=>'Bolívar',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'15',
                'Description'=>'Boyacá',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'17',
                'Description'=>'Caldas',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'18',
                'Description'=>'Caquetá',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'85',
                'Description'=>'Casanare',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'19',
                'Description'=>'Cauca',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'20',
                'Description'=>'Cesar',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'27',
                'Description'=>'Chocó',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'23',
                'Description'=>'Córdoba',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'25',
                'Description'=>'Cundinamarca',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'94',
                'Description'=>'Guainía',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'95',
                'Description'=>'Guaviare',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'41',
                'Description'=>'Huila',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'44',
                'Description'=>'La Guajira',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'47',
                'Description'=>'Magdalena',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'50',
                'Description'=>'Meta',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'52',
                'Description'=>'Nariño',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'54',
                'Description'=>'Norte de Santander',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'86',
                'Description'=>'Putumayo',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'63',
                'Description'=>'Quindío',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'66',
                'Description'=>'Risaralda',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'88',
                'Description'=>'San Andrés y Providencia',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'68',
                'Description'=>'Santander',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'70',
                'Description'=>'Sucre',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'73',
                'Description'=>'Tolima',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'76',
                'Description'=>'Valle del Cauca',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'97',
                'Description'=>'Vaupés',
                'pais_cod'=>'CO'
            ]
        );
        DB::table('departamento')->insert(
            [
                'cod'=>'99',
                'Description'=>'Vichada',
                'pais_cod'=>'CO'
            ]
        );
        
    }
}
