<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class paisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('pais')->insert(
            [
                'cod'=>'0',
                'Description'=>'No definido'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'AF',
                'Description'=>'Afganistán'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'AX',
                'Description'=>'Åland'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'AL',
                'Description'=>'Albania'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'DE',
                'Description'=>'Alemania'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'AD',
                'Description'=>'Andorra'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'AO',
                'Description'=>'Angola'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'AI',
                'Description'=>'Anguila'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'AQ',
                'Description'=>'Antártida'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'AG',
                'Description'=>'Antigua y Barbuda'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'SA',
                'Description'=>'Arabia Saudita'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'DZ',
                'Description'=>'Argelia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'AR',
                'Description'=>'Argentina'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'AM',
                'Description'=>'Armenia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'AW',
                'Description'=>'Aruba'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'AU',
                'Description'=>'Australia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'AT',
                'Description'=>'Austria'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'AZ',
                'Description'=>'Azerbaiyán'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'BS',
                'Description'=>'Bahamas'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'BD',
                'Description'=>'Bangladés'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'BB',
                'Description'=>'Barbados'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'BH',
                'Description'=>'Baréin'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'BE',
                'Description'=>'Bélgica'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'BZ',
                'Description'=>'Belice'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'BJ',
                'Description'=>'Benín'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'BM',
                'Description'=>'Bermudas'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'BY',
                'Description'=>'Bielorrusia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'BO',
                'Description'=>'Bolivia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'BQ',
                'Description'=>'Bonaire, San Eustaquio y Saba'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'BA',
                'Description'=>'Bosnia y Herzegovina'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'BW',
                'Description'=>'Botsuana'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'BR',
                'Description'=>'Brasil'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'BN',
                'Description'=>'Brunéi'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'BG',
                'Description'=>'Bulgaria'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'BF',
                'Description'=>'Burkina Faso'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'BI',
                'Description'=>'Burundi'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'BT',
                'Description'=>'Bután'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'CV',
                'Description'=>'Cabo Verde'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'KH',
                'Description'=>'Camboya'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'CM',
                'Description'=>'Camerún'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'CA',
                'Description'=>'Canadá'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'QA',
                'Description'=>'Catar'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'TD',
                'Description'=>'Chad'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'CL',
                'Description'=>'Chile'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'CN',
                'Description'=>'China'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'CY',
                'Description'=>'Chipre'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'CO',
                'Description'=>'Colombia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'KM',
                'Description'=>'Comoras'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'KP',
                'Description'=>'Corea del Norte'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'KR',
                'Description'=>'Corea del Sur'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'CI',
                'Description'=>'Costa de Marfil'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'CR',
                'Description'=>'Costa Rica'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'HR',
                'Description'=>'Croacia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'CU',
                'Description'=>'Cuba'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'CW',
                'Description'=>'Curazao'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'DK',
                'Description'=>'Dinamarca'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'DM',
                'Description'=>'Dominica'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'EC',
                'Description'=>'Ecuador'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'EG',
                'Description'=>'Egipto'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'SV',
                'Description'=>'El Salvador'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'AE',
                'Description'=>'Emiratos Árabes Unidos'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'ER',
                'Description'=>'Eritrea'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'SK',
                'Description'=>'Eslovaquia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'SI',
                'Description'=>'Eslovenia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'ES',
                'Description'=>'España'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'US',
                'Description'=>'Estados Unidos'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'EE',
                'Description'=>'Estonia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'ET',
                'Description'=>'Etiopía'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'PH',
                'Description'=>'Filipinas'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'FI',
                'Description'=>'Finlandia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'FJ',
                'Description'=>'Fiyi'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'FR',
                'Description'=>'Francia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'GA',
                'Description'=>'Gabón'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'GM',
                'Description'=>'Gambia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'GE',
                'Description'=>'Georgia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'GH',
                'Description'=>'Ghana'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'GI',
                'Description'=>'Gibraltar'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'GD',
                'Description'=>'Granada'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'GR',
                'Description'=>'Grecia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'GL',
                'Description'=>'Groenlandia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'GP',
                'Description'=>'Guadalupe'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'GU',
                'Description'=>'Guam'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'GT',
                'Description'=>'Guatemala'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'GF',
                'Description'=>'Guayana Francesa'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'GG',
                'Description'=>'Guernsey'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'GN',
                'Description'=>'Guinea'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'GW',
                'Description'=>'Guinea-Bisáu'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'GQ',
                'Description'=>'Guinea Ecuatorial'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'GY',
                'Description'=>'Guyana'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'HT',
                'Description'=>'Haití'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'HN',
                'Description'=>'Honduras'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'HK',
                'Description'=>'Hong Kong'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'HU',
                'Description'=>'Hungría'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'IN',
                'Description'=>'India'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'ID',
                'Description'=>'Indonesia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'IQ',
                'Description'=>'Irak'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'IR',
                'Description'=>'Irán'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'IE',
                'Description'=>'Irlanda'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'BV',
                'Description'=>'Isla Bouvet'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'IM',
                'Description'=>'Isla de Man'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'CX',
                'Description'=>'Isla de Navidad'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'IS',
                'Description'=>'Islandia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'KY',
                'Description'=>'Islas Caimán'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'CC',
                'Description'=>'Islas Cocos'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'CK',
                'Description'=>'Islas Cook'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'FO',
                'Description'=>'Islas Feroe'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'GS',
                'Description'=>'Islas Georgias del Sur y Sandwich del Sur'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'HM',
                'Description'=>'Islas Heard y McDonald'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'FK',
                'Description'=>'Islas Malvinas'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'MP',
                'Description'=>'Islas Marianas del Norte'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'MH',
                'Description'=>'Islas Marshall'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'PN',
                'Description'=>'Islas Pitcairn'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'SB',
                'Description'=>'Islas Salomón'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'TC',
                'Description'=>'Islas Turcas y Caicos'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'UM',
                'Description'=>'Islas ultramarinas de Estados Unidos'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'VG',
                'Description'=>'Islas Vírgenes Británicas'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'VI',
                'Description'=>'Islas Vírgenes de los Estados Unidos'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'IL',
                'Description'=>'Israel'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'IT',
                'Description'=>'Italia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'JM',
                'Description'=>'Jamaica'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'JP',
                'Description'=>'Japón'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'JE',
                'Description'=>'Jersey'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'JO',
                'Description'=>'Jordania'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'KZ',
                'Description'=>'Kazajistán'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'KE',
                'Description'=>'Kenia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'KG',
                'Description'=>'Kirguistán'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'KI',
                'Description'=>'Kiribati'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'KW',
                'Description'=>'Kuwait'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'LA',
                'Description'=>'Laos'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'LS',
                'Description'=>'Lesoto'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'LV',
                'Description'=>'Letonia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'LB',
                'Description'=>'Líbano'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'LR',
                'Description'=>'Liberia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'LY',
                'Description'=>'Libia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'LI',
                'Description'=>'Liechtenstein'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'LT',
                'Description'=>'Lituania'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'LU',
                'Description'=>'Luxemburgo'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'MO',
                'Description'=>'Macao'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'MK',
                'Description'=>'Macedonia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'MG',
                'Description'=>'Madagascar'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'MY',
                'Description'=>'Malasia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'MW',
                'Description'=>'Malaui'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'MV',
                'Description'=>'Maldivas'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'ML',
                'Description'=>'Malí'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'MT',
                'Description'=>'Malta'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'MA',
                'Description'=>'Marruecos'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'MQ',
                'Description'=>'Martinica'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'MU',
                'Description'=>'Mauricio'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'MR',
                'Description'=>'Mauritania'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'YT',
                'Description'=>'Mayotte'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'MX',
                'Description'=>'México'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'FM',
                'Description'=>'Micronesia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'MD',
                'Description'=>'Moldavia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'MC',
                'Description'=>'Mónaco'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'MN',
                'Description'=>'Mongolia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'ME',
                'Description'=>'Montenegro'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'MS',
                'Description'=>'Montserrat'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'MZ',
                'Description'=>'Mozambique'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'MM',
                'Description'=>'Myanmar'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'NA',
                'Description'=>'Namibia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'NR',
                'Description'=>'Nauru'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'NP',
                'Description'=>'Nepal'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'NI',
                'Description'=>'Nicaragua'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'NE',
                'Description'=>'Níger'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'NG',
                'Description'=>'Nigeria'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'UN',
                'Description'=>'Niue'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'NF',
                'Description'=>'Norfolk'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'NO',
                'Description'=>'Noruega'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'NC',
                'Description'=>'Nueva Caledonia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'NZ',
                'Description'=>'Nueva Zelanda'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'OM',
                'Description'=>'Omán'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'NL',
                'Description'=>'Países Bajos'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'PK',
                'Description'=>'Pakistán'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'PW',
                'Description'=>'Palaos'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'PS',
                'Description'=>'Palestina'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'PA',
                'Description'=>'Panamá'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'PG',
                'Description'=>'Papúa Nueva Guinea'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'PY',
                'Description'=>'Paraguay'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'PE',
                'Description'=>'Perú'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'PF',
                'Description'=>'Polinesia Francesa'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'PL',
                'Description'=>'Polonia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'PT',
                'Description'=>'Portugal'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'PR',
                'Description'=>'Puerto Rico'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'GB',
                'Description'=>'Reino Unido'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'EH',
                'Description'=>'República Árabe Saharaui Democrática'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'CF',
                'Description'=>'República Centroafricana'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'CZ',
                'Description'=>'República Checa'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'CG',
                'Description'=>'República del Congo'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'CD',
                'Description'=>'República Democrática del Congo'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'DO',
                'Description'=>'República Dominicana'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'RE',
                'Description'=>'Reunión'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'RW',
                'Description'=>'Ruanda'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'RO',
                'Description'=>'Rumania'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'RU',
                'Description'=>'Rusia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'WS',
                'Description'=>'Samoa'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'AS',
                'Description'=>'Samoa Americana'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'BL',
                'Description'=>'San Bartolomé'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'KN',
                'Description'=>'San Cristóbal y Nieves'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'SM',
                'Description'=>'San Marino'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'MF',
                'Description'=>'San Martín'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'PM',
                'Description'=>'San Pedro y Miquelón'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'VC',
                'Description'=>'San Vicente y las Granadinas'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'SH',
                'Description'=>'Santa Elena, Ascensión y Tristán de Acuña'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'LC',
                'Description'=>'Santa Lucía'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'ST',
                'Description'=>'Santo Tomé y Príncipe'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'SN',
                'Description'=>'Senegal'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'RS',
                'Description'=>'Serbia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'SC',
                'Description'=>'Seychelles'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'SL',
                'Description'=>'Sierra Leona'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'SG',
                'Description'=>'Singapur'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'SX',
                'Description'=>'Sint Maarten'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'SY',
                'Description'=>'Siria'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'SO',
                'Description'=>'Somalia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'LK',
                'Description'=>'Sri Lanka'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'SZ',
                'Description'=>'Suazilandia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'ZA',
                'Description'=>'Sudáfrica'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'SD',
                'Description'=>'Sudán'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'SS',
                'Description'=>'Sudán del Sur'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'SE',
                'Description'=>'Suecia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'CH',
                'Description'=>'Suiza'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'SR',
                'Description'=>'Surinam'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'SJ',
                'Description'=>'Svalbard y Jan Mayen'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'TH',
                'Description'=>'Tailandia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'TW',
                'Description'=>'Taiwán (República de China)'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'TZ',
                'Description'=>'Tanzania'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'TJ',
                'Description'=>'Tayikistán'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'IO',
                'Description'=>'Territorio Británico del Océano Índico'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'TF',
                'Description'=>'Tierras Australes y Antárticas Francesas'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'TL',
                'Description'=>'Timor Oriental'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'TG',
                'Description'=>'Togo'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'TK',
                'Description'=>'Tokelau'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'TO',
                'Description'=>'Tonga'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'TT',
                'Description'=>'Trinidad y Tobago'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'TN',
                'Description'=>'Túnez'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'TM',
                'Description'=>'Turkmenistán'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'TR',
                'Description'=>'Turquía'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'TV',
                'Description'=>'Tuvalu'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'UA',
                'Description'=>'Ucrania'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'UG',
                'Description'=>'Uganda'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'UY',
                'Description'=>'Uruguay'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'UZ',
                'Description'=>'Uzbekistán'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'VU',
                'Description'=>'Vanuatu'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'VA',
                'Description'=>'Vaticano, Ciudad del'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'VE',
                'Description'=>'Venezuela'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'VN',
                'Description'=>'Vietnam'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'WF',
                'Description'=>'Wallis y Futuna'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'YE',
                'Description'=>'Yemen'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'DJ',
                'Description'=>'Yibuti'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'ZM',
                'Description'=>'Zambia'
            ]
        );
        DB::table('pais')->insert(
            [
                'cod'=>'ZW',
                'Description'=>'Zimbabue'
            ]
        );
        
    }
}
