<?php

    /* common */

    define('ZERO_OF_1_PAGES', '{0} de {1} paginas');
    define('ZERO_1_OF_2_ICONS', '{0} - {1} de {2} iconos');
    define('ADD_NEW_ITEM', 'Añadir nuevo item');
    define('ADD_NEW_SNIPPET', 'Añadir nuevo Snippet');
    define('ALERT_STYLE', 'Estilo de alerta');
    define('ALERT_TEXT', 'Texto alerta');
    define('ALT_TEXT', 'Texto alternativo');
    define('APPEND', 'Anexar');
    define('BADGE_TEXT', 'Texto Badge');
    define('BLOCKS_WILL_BE_STACKED_ON_XS_DEVICES', 'Bloques se apilarán en dispositivos xs (smartphones)');
    define('BLOCKS_WILL_BE_STACKED_ON_XS_SMALL_DEVICES', 'Bloques se apilarán en xs y pequeños dispositivos (smartphones y pequeñas tabletas)');
    define('BLOCKS_WILL_BE_STACKED_ON_XS_SMALL_MEDIUM_DEVICES', 'Bloques se apilarán en XS, pequeño y dispositivos medianos (smartphones y tablets)');
    define('BLOCKS_WILL_NEVER_BE_STACKED', 'Bloques Nunca se apilarán');
    define('BREAKPOINT', 'Punto de ruptura');
    define('BROWSE', 'Explorar');
    define('BUTTON_SIZE', 'Tamaño de Botón');
    define('BUTTON_STYLE', 'Estilo de botón');
    define('CANCEL', 'Cancelar');
    define('CELLS', 'Celdas');
    define('CENTER', 'CENTRO');
    define('CHOOSE_SNIPPET_TO_EDIT', 'Por favor, elija un snippet a editar');
    define('CHOOSE_SNIPPET_TO_DELETE', 'Por favor, elija un snippet a eliminar');
    define('CLOSE_BUTTON', 'CERRAR BOTON');
    define('CODE', 'Código');
    define('COLOR', 'Color');
    define('COLS', 'Columnas');
    define('CONTENT', 'Contenido');
    define('CURRENT', 'Actual');
    define('CUSTOM', 'Personalizado');
    define('DELETE_CONST', 'Eliminar');
    define('DELETE_THIS_ITEM', 'Eliminar este item');
    define('DISABLED', 'Deshabilitado');
    define('DISABLED_ELEMENTS_WILL_NOT_BE_EDITABLE_IN_TINYMCE_EDITOR', 'Elementos de desactivados no será editable en el editor');
    define('DISMISSABLE', 'Dismissable');
    define('DRAG_DROP_ELEMENTS_TO_PREVIEW', 'Arrastrar y soltar elementos para la vista previa');
    define('DROP_ELEMENTS_HERE', 'Coloque elementos equí');
    define('EDIT', 'Editar');
    define('FOOTER', 'PIE');
    define('FOOTER_CONTENT', 'Contenido de pie');
    define('HEADING', 'Encabezado');
    define('HEADING_CONTENT', 'Contenido encabezado');
    define('HEIGHT', 'Altura');
    define('HORIZONTAL_HEADER', 'Encabezado Horizontal');
    define('HTML_AUTHORIZED', 'Autorizar HTML');
    define('ICON', 'Icono');
    define('ICON_SIZE', 'Tamaño de icono');
    define('IMAGE', 'Imágen');
    define('IMAGE_STYLE', 'Estilo de imágen');
    define('ITEMS', 'Items');
    define('LABEL_STYLE', 'Estilo de etiqueta');
    define('LABEL_TEXT', 'Texto de etiqueta');
    define('LINK', 'Link');
    define('MAIN_CONTENT', 'Contenido principal');
    define('MY_FANTASTIC_BUTTON', 'Mi botón Fantástico');
    define('NEW_CONST', 'Nuevo');
    define('NEW_ITEM', 'Nuevo Item');
    define('NEXT', 'Siguiente');
    define('NO', 'NO');
    define('NO_CLOSE_BUTTON', 'NO CERRAR BOTON');
    define('NO_FOOTER', 'SIN PIE');
    define('NO_HEADING', 'SIN ENCABEZADO');
    define('NO_IMAGE_SELECTED', 'No selectiono imágen');
    define('NO_SNIPPET_TO_DISPLAY', 'Sin snippet para mostrar');
    define('OK', 'OK');
    define('OTHERS', 'Otros');
    define('PANEL_CONTENT', 'Contenido del panel');
    define('PANEL_STYLE', 'Estilo de panel');
    define('PANEL_TITLE', 'Título de panel');
    define('PHP_FORBIDDEN', 'Scripts PHP están prohibidos');
    define('PLEASE_CHOOSE_AN_IMAGE', 'Por favor, elija un archivo de imágen');
    define('PLEASE_END_EDIT', 'Por favor, antes de terminar la edición verifique la información');
    define('POSITION', 'Posición');
    define('PREPEND', 'Anteponer');
    define('PREVIEW', 'Vista previa');
    define('PREVIOUS', 'Anterior');
    define('PUSH_TO_THE_SIDES', 'EMPUJAR A LOS LADOS');
    define('ROWS_COLS', 'Filas/columnas');
    define('RESPONSIVE', 'Responsivo');
    define('ROW_COL_EDITION_IS_DISABLED_FOR_EDITED_TABLES', 'Edición Fila / columna está desactivada para las tablas editadas <br> Usted puede agregar fácilmente / eliminar filas y Columnas directamente en el editor.');
    define('SCRIPT_FORBIDDEN', 'Etiquetas de secuencias de comandos están prohibidos');
    define('SECTIONS', 'Secciones');
    define('SIZE', 'Tamaño');
    define('SNIPPET_ADDED', 'Snippet ha sido añadido');
    define('SNIPPET_DELETED', 'Snippet ha sido eliminado');
    define('SNIPPET_UPDATED', 'Snippet ha sido actualizado');
    define('SNIPPETS', 'Snippets');
    define('STRUCTURE', 'Estructura');
    define('STYLE', 'Estilo');
    define('TAG', 'Etiqueta');
    define('TEXT', 'Texto');
    define('TITLE', 'Título');
    define('TITLE_MUST_MATCH', 'Le titre ne doit contenir que des caractères alphanumériques, tirets et espaces (maximum 150 caractères).');
    define('VALUE', 'Valor');
    define('VERTICAL_HEADER', 'Encabezado vertical');
    define('WIDTH', 'Ancho');
    define('WRONG_DATA', 'Datos erróneos');
    define('YES', 'SI');
    define('YOUR_TEXT', 'Tu texto');
